// <auto-generated />
using System;
using EF_CORE_EMPTY_CONTROLLER.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_CORE_EMPTY_CONTROLLER.Migrations
{
    [DbContext(typeof(BookAuthorContext))]
    partial class BookAuthorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_CORE_EMPTY_CONTROLLER.Models.Author", b =>
                {
                    b.Property<int>("AuthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthId"));

                    b.Property<string>("AuthName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthId = 11,
                            AuthName = "Robert Baratheon"
                        },
                        new
                        {
                            AuthId = 12,
                            AuthName = "Jon Stark"
                        });
                });

            modelBuilder.Entity("EF_CORE_EMPTY_CONTROLLER.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int>("AuthId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PublicationYear")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthId = 11,
                            Price = 4500m,
                            PublicationYear = new DateOnly(2002, 1, 15),
                            Title = "Winterfell"
                        },
                        new
                        {
                            BookId = 2,
                            AuthId = 12,
                            Price = 5000m,
                            PublicationYear = new DateOnly(2005, 11, 23),
                            Title = "Vale"
                        });
                });

            modelBuilder.Entity("EF_CORE_EMPTY_CONTROLLER.Models.Book", b =>
                {
                    b.HasOne("EF_CORE_EMPTY_CONTROLLER.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("EF_CORE_EMPTY_CONTROLLER.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
